export enum AppPaths {
  REGISTER_CLIENT = '/register/client',
  REGISTER_SALON_OWNER = '/register/salon-owner',
  LOGIN = '/login',
  HOME = '/',
  UNAUTHORIZED = '/unauthorized',
  SEARCH_SERVICE = '/search/service',
  SEARCH_LOCATION = '/search/location',
  SEARCH_RESULTS = '/search/results',
  VIEW_MORE_RECOMMENDED = '/salons/view-more/recommended',
  VIEW_MORE_POPULAR = '/salons/view-more/popular',
  VIEW_MORE_NEWEST = '/salons/view-more/newest',
  DATE_TIME = '/search/date-time',
  OWNER_SALON_INTRO = '/owner-salon-intro',
  CLIENT_PROFILE = '/profile/client',
  LOADING = '/loading',
}
